<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rosa Animada y TE AMO</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="container">
    <div class="rose"></div>
    <div class="message">
      <h1>TE AMO</h1>
    </div>
  </div>

  <script src="script.js"></script>
</body>
</html>
